export interface Member {
  name: string
  title: string
  text: string[]
  img: string
  country: string
  social: string
  links: Link[]
}

export interface Link {
  talks?: string
  writing?: string
}

export const team: Member[] = [
  {
    name: "Emma Cushman",
    title: "Engineering",
    text: [
      "Something I'm proud of at Ashby...Every time other sites changed their HTML, a scraping feature in our chrome extension would break and we had to wait days for a new version to be reviewed by Google.\n\nIn my first week, I converted the web scraping code in our chrome extension from a combination of CSS selectors and Typescript to API driven XPath selectors. Now we can adjust scraping without releasing!\n",
      "Something I've helped the team with...During a post-mortem, we identified that frontend errors were getting missed during QA. I built a widget that shows a summary of console.log errors in-app so they're harder to miss.\n",
      'Most surprising thing about Ashby...Everyone talks about the importance of using async communication whenever possible. It was still surprising the first time someone at Ashby cancelled a big meeting with the explanation "this can just be an email"!\n',
    ],
    img: "https://www.ashbyhq.com/images/emma.jpg",
    country: "🇺🇸",
    social: "https://www.linkedin.com/in/emmacushman/",
    links: [],
  },
  {
    name: "João Carvalho",
    title: "Engineering",
    text: [
      "Something I'm proud of at Ashby...I moved our calendar and email sync from a brute force cron job to real-time sync. It's helped both customers and our team: customers now have the most up-to-date information when scheduling and following up with candidates and we've able to scale sync as we grow with minimal effort.\n",
      "Something I've helped the team with...I've added monitoring and observability to a lot of our infrastructure at Ashby: Datadog monitors to alert us when things go wrong, linking Sentry issues to DataDog traces, logging SQL explains for inefficient SQL generated by our query engine. It's greatly reduced the stress of being on-call, provided context when debugging a product issue, and helped us proactively catch performance bottlenecks before they become a real problem.\n",
      "Most surprising thing about Ashby...The impact that a small, engineering-focused team can have in building and shaping such a complex product.\n",
    ],
    img: "https://www.ashbyhq.com/images/joao.jpg",
    country: "🇵🇹",
    social: "https://www.linkedin.com/in/joaopecarvalho/",
    links: [
      {
        talks: "https://jcarvalho.dev/talks/",
      },
    ],
  },
  {
    name: "Benjamin Encz",
    title: "Cofounder & CEO",
    text: [
      "Something I'm proud of at Ashby...I've designed and created some of the early building blocks we use to build new features (think Legos). It's been great to see the team embrace this way of building and watch the building blocks evolve without my help!\n",
      "Something I've helped the team with...I've built and continue to expand the internal knowledge base of our industry and our customers. It's critical to help the team make independent product and engineering decisions.\n",
      "Most surprising thing about Ashby...The team has consistently focused on the long term even as I've stepped away from engineering.\n",
    ],
    img: "https://www.ashbyhq.com/images/benji.jpeg",
    country: "🇺🇸",
    social: "https://www.linkedin.com/in/benjaminencz/",
    links: [
      {
        talks: "http://blog.benjamin-encz.de/speaking/",
      },
      {
        writing: "http://blog.benjamin-encz.de/",
      },
    ],
  },
  {
    name: "Ravan Charles",
    title: "Customer Onboarding & Support",
    text: [
      "Something I'm proud of at Ashby...I built Ashby University, our customer help center. It's been rewarding to see how helpful it is to customers as they onboard and learn new features.\n",
      "Something I've helped the team with...I designed and setup our changelog process to make it really easy for engineers to let our go-to-market team know which new features are ready to share with customers. All engineers have to do is tag a Pull Request in GitHub!\n",
      "Most surprising thing about Ashby...How awesome the humans are! Everyone on the team is as kind and collaborative as they are talented.\n",
    ],
    img: "https://www.ashbyhq.com/images/ravan.jpg",
    country: "🇺🇸",
    social: "https://www.linkedin.com/in/ravan-charles-she-her-43a95140/",
    links: [],
  },
  {
    name: "Kaitlyn Crawley",
    title: "Engineering",
    text: [
      "Something I'm proud of at Ashby...I designed and built our HRIS integrations with Rippling and BambooHR. Instead of manually copying data on hired candidates from Ashby to their HRIS, customers can do it with the click of a button!\n",
      "Something I've helped the team with...I built a script that enabled our team to import our customers' candidate data from CSV files. It's enabled us to work with technology partners and recruiting firms that haven't yet integrated with Ashby.\n",
      "Most surprising thing about Ashby...The flexibility and breadth of the product was definitely something that surprised me when I joined Ashby. I was impressed by all of the existing capabilities of the product, and I'm excited to help expand and improve on what we've already built!\n",
    ],
    img: "https://www.ashbyhq.com/images/kaitlyn.jpeg",
    country: "🇺🇸",
    social: "https://www.linkedin.com/in/kaitlyn-crawley-0366097a/",
    links: [],
  },
  {
    name: "Ben Asher",
    title: "Engineering",
    text: [
      "Something I'm proud of at Ashby...I built Ashby's in-app e-signature feature. Before, our customers had to generate the document in Ashby, upload it to an e-signature service like DocuSign, set up the signature blocks, get the signatures, download the signed document, and upload it back to Ashby. Now this entire process is automated!",
      "Something I've helped the team with...In my first month, I upgraded many of our core libraries to the latest major version (e.g. Create React App) and migrated us from TSLint to ESLint. With these changes, other engineers had faster build and reload times and more issues caught in CI (versus in production)!\n",
      'Most surprising thing about Ashby...I continue to be surprised at how well we live our "build for the long term" engineering principle. It\'s amazing how often I find myself building off of the building blocks of others, versus having to build new one-off components.\n',
    ],
    img: "https://www.ashbyhq.com/images/ben.png",
    country: "🇺🇸",
    social: "https://www.linkedin.com/in/benasher44/",
    links: [
      {
        talks: "https://benasher.co/about/",
      },
      {
        writing: "https://benasher.co/",
      },
    ],
  },
  {
    name: "Sylvie Paquette",
    title: "Quality Assurance",
    text: [
      "Something I'm proud of at Ashby...I've defined our QA process from the ground up: from how new features get QA-ed to how bugs get repro steps to our test plans for each feature.\n",
      "Something I've helped the team with...I created a bug reporting process to bridge the gap between our customer service and engineering teams. Incoming bugs can quickly and smoothly be triaged and assigned to the right engineers for a fix.\n",
      "Most surprising thing about Ashby...One of the things that drew me to Ashby is still one of the things that most amazes me - that such a complex, impactful product can come to life with a small (so far!), mostly remote, focused team.\n",
    ],
    img: "https://www.ashbyhq.com/images/sylvie.jpg",
    country: "🇨🇦",
    social: "https://www.linkedin.com/in/sylvie-paquette-257988136/",
    links: [],
  },
  {
    name: "Tom Quist",
    title: "Engineering",
    text: [
      "Something I'm proud of at Ashby...I implemented syncing data from other recruiting software into Ashby. It opened up Ashby's powerful reporting features to customers who can't use our all-in-one product yet.\n",
      "Something I've helped the team with...I sped up our automated tests on CI by 10x; they now run in under 10 minutes. We're able to make changes and deploy much faster than we could before.\n",
      "Most surprising thing about Ashby...What's always surprising to me, is how each existing feature in Ashby instantly produces some additional value to a new feature. For example, when I worked on a data integration feature all the data that got integrated was automatically exposed to Ashby's analytics features. If you build something at Ashby, very often you'll be able to take some existing building blocks and use them in a new feature with only a little bit of glue code.\n",
    ],
    img: "https://www.ashbyhq.com/images/tom.jpg",
    country: "🇩🇪",
    social: "https://www.linkedin.com/in/tom-quist-0925a199/",
    links: [],
  },
  {
    name: "Jacob Miller",
    title: "Sales & Business Development",
    text: [
      "Something I'm proud of at Ashby...In my first 30 days, I booked 15 outbound meetings with great companies using a new email messaging strategy built around referencing the VP Eng. The approach received positive feedback from prospects; a talent leader said it was the best cold email he'd received 😀\n",
      "Something I've helped the team with...I proposed and implemented Guru as a knowledge sharing solution for sales and customer support. It allows our sales knowledge to be easily accessible via chrome extension. It's helpful for teammates who join the go-to-market team and need quick, digestible answers to common customer-facing questions.\n",
      "Most surprising thing about Ashby...Definitely the minimization of Slack! It's been a huge net-positive on my productivity and general wellbeing. I even posted about it recently on LinkedIn.\n",
    ],
    img: "https://www.ashbyhq.com/images/jacob.png",
    country: "🇺🇸",
    social: "https://www.linkedin.com/in/jacobmiller1210/",
    links: [
      {
        writing:
          "https://www.linkedin.com/in/jacobmiller1210/detail/recent-activity/posts/",
      },
    ],
  },
  {
    name: "Graham Murdoch",
    title: "Design & Engineering",
    text: [
      "Something I'm proud of at Ashby...I designed and implemented the ability to multi-select candidates in our pipeline view and perform bulk actions. Customers use it multiple times daily and it saves them a lot of clicks!\n",
      "Something I've helped the team with...I revamped our input field components in our design system with a new more flexible API for layout and interactions. Other engineers have been able to quickly create visually pleasing forms and profile pages with minimal effort!\n",
      "Most surprising thing about Ashby...I'm surprised at how quickly the market has embraced us as a critical improvement to existing tools. People are really blown away when they see what we can do for them.\n",
    ],
    img: "https://www.ashbyhq.com/images/graham.jpg",
    country: "🇺🇸",
    social: "https://www.linkedin.com/in/sandgraham/",
    links: [
      {
        writing: "https://baseweb.design/blog/phone-input/",
      },
    ],
  },
  {
    name: "Kyra",
    title: "Customer Success",
    text: [
      "Something I'm excited to work on at Ashby...I'm thrilled to build out the Customer Success function at Ashby so that we can scale. Our customers love the product and use it to hit important KPIs. We hear a lot that our hands on support and onboarding is a differentiator and I'm excited to design a system that can sustainably grow with us. No matter how big we get, we'll be putting customers first and aiming to delight every day! \n",
      "My onboarding experience at Ashby...My onboarding experience has been great so far! Ashby is super powerful, and the team has helped me dive right in and learn how much this tool can really do. I'm so appreciative of how much the team is willing to help out and hop on Zooms to talk through things.\n",
      "Most surprising thing about Ashby...That the weekly 30 minute meeting, where each team member provides an update on what they're focused on for the week, is super informative and somehow always ends early!? I'm consistently impressed by how efficient Ashby is, how thoughtful people are about each other's time, and how connected the team is.",
    ],
    img: "https://www.ashbyhq.com/images/kyra.jpg",
    country: "🇺🇸",
    social: "https://www.linkedin.com/in/kyra-vargas-739b03b1/",
    links: [],
  },
  {
    name: "Arjun Nayini",
    title: "Engineering",
    text: [
      "Something I'm proud of at Ashby...I built our Sourcing module from idea to implementation. The hiring process starts with sourcing great candidates and it's great to see how much our customers depend on it.\n",
      "Something I've helped the team with...At Ashby, we encourage everyone to write up and share learnings they have over the course of their work. I've helped contribute to the large repository of interesting and quirky technical lessons we've learned as a team. Writing and sharing these has really helped me consistently grow my skills while I've been here.\n",
      "Most surprising thing about Ashby...How much we've accomplished with a small team in such a short period of time. We've built powerful pieces of infrastructure that really give us the leverage to build features for our customers quickly and reliably.\n",
    ],
    img: "https://www.ashbyhq.com/images/arjun.jpg",
    country: "🇺🇸",
    social: "https://www.linkedin.com/in/arjun-nayini-2b677117/",
    links: [],
  },
  {
    name: "Khay Nguyen",
    title: "Business Operations",
    text: [
      "Something I'm proud of at Ashby...One of the joys of working as a team of one is  I’m able to impact (and learn about) many facets of the business, from sales to finance. I formalized deal flow management in our CRM, built all our sales metrics and ARR analytics from scratch, and wrangled our billings and invoicing process.\n",
      "Something I've helped the team with...I automated handoff of a customer from sales to customer success by configuring our CRM to automatically create customer check-in reminders once a deal is closed. Before this, we weren't able to keep track of customers and make sure they were having a great experience!\n",
      "Most surprising thing about Ashby...I joined Ashby when it was 7 people and I was expecting it to be more chaotic and disorganized (like the typical startup journey). While there are constantly new problems to solve, I'm delighted that decisions are made rationally with long-term success in mind. I also appreciate the clear standards around effective communication practices and documentation, something that most companies wait too long to implement.\n",
    ],
    img: "https://www.ashbyhq.com/images/khay.png",
    country: "🇺🇸",
    social: "https://www.linkedin.com/in/khaynguyen/",
    links: [],
  },
  {
    name: "Florian Krüger",
    title: "Engineering",
    text: [
      "Something I'm proud of at Ashby...I created a feature that enables our users to import data from CSV files and map it to any record or related record in Ashby. Previously, customers had to reach out to support, support reached out to an engineer, and the engineer had to configure and run a script to import the data. Now it's entirely self-serve.\n",
      "Something I've helped the team with...Originally meant to be a feature for our users, I added the ability to refresh the cache for reports. It coincidentally made the lives of engineers easier. If they changed any logic during development, they could easily refresh the cache to see the changes.\n",
      "Most surprising thing about Ashby...It's amazing to see how every single person on the team is dedicated to building the right thing the right way for the long term. I've never experienced a group of people being so aligned in creating and maintaining best practices, documentation, and tooling to make the best possible product.\n",
    ],
    img: "https://www.ashbyhq.com/images/florian.png",
    country: "🇩🇪",
    social: "https://www.linkedin.com/in/floriankrueger1985/",
    links: [],
  },
  {
    name: "Joel Reske",
    title: "Engineering",
    text: [
      "Something I'm proud of at Ashby...I built Ashby's auto-reject feature; it allows customers to create flexible rules to automatically reject candidates who don't fulfill certain requirements. It saves our customers a lot of time and, as part of this project, I improved the extensibility of the underlying business process engine that powers many of our features (including this one).\n",
      "Something I've helped the team with...Building a remote culture isn't easy and, as we've grown, it's been harder to get to know everyone without social events. I started a monthly game \"night\" (we play during work hours) to help us get to know each other and bond as a team.\n",
      "Most surprising thing about Ashby...Even as a startup, we're building great generic building blocks for the long haul.\n",
    ],
    img: "https://www.ashbyhq.com/images/joel.jpg",
    country: "🇺🇸",
    social: "https://www.linkedin.com/in/joel-reske/",
    links: [],
  },
  {
    name: "Aaron Norby",
    title: "Engineering",
    text: [
      "Something I'm proud of at Ashby...I moved our report generation to a worker-based infrastructure with caching. Running Ashby reports is computationally expensive because of how flexible it is and with this change, we've been able to increase the number and size of our customers without impacting our other features and services.\n",
      "Something I've helped the team with...I built our database schema migration system. It compares our Typescript models to what exists in our database and automatically generates an up and down migration that adds, removes, or updates tables, columns, foreign keys, and constraints.\n",
      "Most surprising thing about Ashby...How complex some of the problems are in recruiting. Giving talent teams the tools to get insights and be productive gives us really interesting problems to solve with software.\n",
    ],
    img: "https://www.ashbyhq.com/images/norby.jpg",
    country: "🇺🇸",
    social: "https://www.linkedin.com/in/anorby/",
    links: [],
  },
  {
    name: "Alli Williams",
    title: "Recruiting",
    text: [
      "Something I'm excited to work on at Ashby...There has already been so much success building a team of talented individuals, but as the first recruiting hire, I am excited to scale the team, create a defined Recruiting function, and keep candidate experience top of mind!\n",
      "My onboarding experience at Ashby...The onboarding experience at Ashby is incredibly efficient as everything is well documented. Being able to refer to how-to documents, originally created for customers, while also being able to read about the long term goals and company vision makes you feel incredibly close to the work that the team has accomplished thus far.\n",
      "Most surprising thing about Ashby...The autonomy! Everyone recognizes that time is precious! Meetings are efficient and in low quantity, so focus time and heads down work comes naturally.",
    ],
    img: "https://www.ashbyhq.com/images/alli.png",
    country: "🇺🇸",
    social: "https://www.linkedin.com/in/allisonrwilliams/",
    links: [],
  },
  {
    name: "Ronald Martin",
    title: "Engineering",
    text: [
      "Something I'm proud of at Ashby...I built a tool that lets candidates directly book their desired interview time with the companies they're talking to, saving hours of back-and-forth communication/coordination time per week! It's like Calendly but with more complexity: you can book with multiple interviewers and each interviewer can be picked from a pool. It wows every customer the first time they use it!\n",
      "Something I've helped the team with...In my first week at Ashby, I created a number of zsh aliases for common commands that I was running frequently. When the next engineer started, I shared the aliases with that person (my onboarding mentee) and didn't think much of that afterward. Over a year later, I discovered that successive newer teammates have been sharing and improving that original set of aliases! We now have our own repository to centrally update and share them.\n",
      'Most surprising thing about Ashby...The common mantra for startups is to build the MVP and iterate as quickly possible. At Ashby, we\'ve instead been betting on a "festina lente" approach; we "hurry slowly." It\'s been amazing to me just how much taking time to build our product *well* has positively impacted both customer and developer happiness.\n',
    ],
    img: "https://www.ashbyhq.com/images/ronald.png",
    country: "🇺🇸",
    social: "https://www.linkedin.com/in/ronaldsmartin/",
    links: [],
  },
  {
    name: "Kevin Connolly",
    title: "Product Manager",
    text: [
      "Something I'm proud of at Ashby...As Ashby grew, I took on the full-time responsibility for our Analytics product. Within that scope, I've brought a dedicated focus to understanding our customers' product journey, starting at the sales demo through onboarding to the ongoing customer experience.\n\nIn working closely with many of our customers, I defined a standard set of dashboards for common use cases and needs in the recruiting space. These reports are now the starting point for every new customer and available immediately, providing access that otherwise would take many weeks of analyst effort. It's amazing to see a talent leader's joy when they get insights into their recruiting process they never had before.\n",
      "Something I've helped the team with...On a topic that's less about the day-to-day of product management, I wanted to help our team members get to know each other in our remote-first world. To help with that, I introduced a people intro slide deck where everyone gets a slide to share more about their personal interests. At all hands, every new employee introduces themselves with that slide. We've been able to learn a lot of interesting things that we would have otherwise never known, and it's a ton of fun!\n",
      "Most surprising thing about Ashby...I joined Ashby primarily because of the people - they're talented and are a rare selection of all-around great coworkers. Apart from that, having seen our product help, enable, and satisfy customers, I've had a growing pride in what we do and what we're building. It was a bit unexpected at first, but now I look at all the other companies in the world that I admire, and I have a sort of excitement at the idea of helping them effectively build the team they need. It's fun and hard work, we have so much to build, but it's really rewarding.\n",
    ],
    img: "https://www.ashbyhq.com/images/kevin.png",
    country: "🇺🇸",
    social: "https://www.linkedin.com/in/adamantine/",
    links: [
      {
        writing: "https://medium.com/@kevinconnolly",
      },
    ],
  },
  {
    name: "Andy Brown",
    title: "Engineering",
    text: [
      "Something I'm excited to work on at Ashby...Optimizing our dynamically generated SQL!\n",
      "My onboarding experience at Ashby...Something unique about starting at Ashby is that you schedule 1-1s with everyone on the team during onboarding. I liked having the opportunity to get to know everyone on a personal level before diving into work.\n",
      "Most surprising thing about Ashby...I’ve been surprised by how mature the company is. The fundamental building blocks available to engineers are robust, and things “just work”, which I think is unusual for a startup of this size.",
    ],
    img: "https://www.ashbyhq.com/images/andy.jpg",
    country: "🇺🇸",
    social: "https://www.linkedin.com/in/andrewebrownaeb0/",
    links: [],
  },
  {
    name: "Abhik Pramanik",
    title: "Cofounder & Engineering",
    text: [
      "Something I'm proud of at Ashby...I built Ashby's design system. It's enabled the team to design and launch well designed products; often without a full-time designer! While we have room to improve, customers consistently comment on how well designed Ashby is.\n",
      "Something I've helped the team with...I implemented code that tagged all client Sentry errors with a link to a video recording of the user session. It was a small change but it continues to help us create repro steps for obscure bugs and fix them, often without a user even reporting it!\n",
      "Most surprising thing about Ashby...I continue to be surprised at the depth we can go with each feature we've built. While we can improve our customer's lives with a first version, it often uncovers even more impactful problems or inefficiencies we can solve. We've only scratched the surface of what Ashby can do for our customers!",
    ],
    img: "https://www.ashbyhq.com/images/abhik.jpg",
    country: "🇺🇸",
    social: "https://www.linkedin.com/in/abhikpramanik",
    links: [],
  },
]
